name: PR

on: [pull_request]

jobs:
  build-n-test:
    name: Build and test
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-deps-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-deps-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.OS }}-deps-
    - name: Install deps
      run: yarn install

    - name: Build js
      run: yarn build

    - name: Run tests
      run: yarn test --coverage


